### ISSUE TITLE
Review GameSceneSetup.md and see if any updates necessary

### ISSUE THREAD

**Issue by dmchaledev** [Maaack/Godot-Game-Template#176]
Good morning Maaack, thank you for your hard work on this template. Is the GameSceneSetup.md file at https://github.com/Maaack/Godot-Game-Template/blob/main/addons/maaacks_game_template/docs/GameSceneSetup.md accurate?

**Comment by Maaack** [comment]
Yes, it is slightly out-of-date. The big difference I'm seeing since the last update has been the addition of the `LevelListManager`, which holds logic previously in `GameUI`. It is connected to the `LevelLoader` and has links to other scenes.

I will make sure to do another pass on it before the next update. Thanks for pointing that out!
