### ISSUE TITLE
LevelLoader still tries to load levels that are missing

### ISSUE THREAD

**Issue by Maaack** [Maaack/Godot-Game-Template#81]
The LevelLoader may try to load an invalid level after:

- deleting a scene from the directory.
- having a `current_level` var that is `> levels.size()`.

This results in some confusing errors.

**Comment by thefinaldegree** [comment]
Ah, this might be what I just discovered a few moments ago.

How I replicated mine:

1. Get a fresh copy of the template
2. run the template, play the provided game scenes, progressing to the third game scene ("Level3")
3. Open the in-game menu and make a change (or otherwise trigger a config write-out)
4. Close the game, remove all game scenes from the scene array except "Level1" (no changes to files/directory)
5. run game again, click 'play'
